project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "**/*.qmd"
  resources:
    - "images/"
    - "publications/images_publications/"
    - "highlights/images_highlights/"

website:
  title: "DigiPols"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: highlights.qmd
        text: Highlights        
      - href: team.qmd
        text: Team        
    logo: images/logo1.png

format:
  html:
    theme: cosmo
    css: styles.css

knitr:
  opts_chunk:
    comment: "#>"
    collapse: true
