project:
  type: website
  output-dir: docs

website:
  title: "DigiPols"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News
      - href: team.qmd
        text: Team
      - href: about.qmd
        text: About
    logo: images/logo.png
  twitter-card: 
    creator: "@dragonstyle" 
    site: "@rstudio"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

knitr:
   opts_chunk:
     fig.path: "images/"
     comment: "#>"
     collapse: true

