project:
  type: website
  output-dir: docs

website:
  title: "DigiPols"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: news.qmd
        text: News
      - href: publications.qmd
        text: Publications      
      - href: team.qmd
        text: Team
      - href: test.qmd
        text: Test
      - href: dashboard.qmd
        text: Dashboard  
    logo: images/logo1.png
  twitter-card: 
    creator: "@dragonstyle" 
    site: "@rstudio"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

knitr:
   opts_chunk:
     fig.path: "images/"
     comment: "#>"
     collapse: true

